Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: opuls-bucket-demo

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d06583a13678c938
      SubnetId: subnet-0fb0cc7b3e4bb324d  # Replace <subnet-id> with your specific Subnet ID
      SecurityGroupIds:      # Specify the security group IDs as a list
        - sg-0a6faafc18ee7b2ea